baseURL = "https://massifsurfer.github.io/nmd-preview/"
languageCode = "ce"
title = "NMD"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "ce"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
