[[navbar]]
  identifier = "projects"
  name = "Проекташ"
  url = "/projects/"
  weight = 2
[[navbar]]
  identifier = "blog"
  name = "Блог"
  url = "/blog/"
  weight = 3
[[navbar]]
  identifier = "resources"
  name = "Ресурсаш"
  url = "/resources/"
  weight = 4